##CREATOR

POST http://localhost:3003/user/register
Content-Type: application/json

{
   "first_name": "John",
    "last_name": "Doe",
    "participation": 40
}

####GET

GET http://localhost:3003/user/getUser
Content-Type: application/json

